#!/usr/bin/python3
# -*- coding: utf-8; mode: python -*-

# BSC Thesis
#
# Author
#  - José Ángel Martín Baos

from config import *
import numpy as np
import picamera.array
import time

class MotionAnalysis(picamera.array.PiMotionAnalysis):
    """Count the number of vehicles that are recorded by the cammera."""
    def __init__(self, camera, count_vehicles):
        super().__init__(camera)
        self.count_vehicles = count_vehicles

    def analyse(self, motion_data):
        """
        Override analyse method from PiMotionAnalysis class. This method receives
        the motion data recorded in a certain frame by the camera sensor and
        process it.

        Input:   motion_data -> Motion data array generated by the camera.
        """
        self.count_vehicles.count(motion_data)
